massive change lel

diff --git a/sa b/sa
--- a/sa
+++ b/sa
@@ -1,10 +1,6 @@
 #!/bin/sh
 
-function sa() {
-	where="xclip-$(cat /tmp/r)"
-	echo -n "$RANDOM$RANDOM" > /tmp/r && \
-	xclip -selection clipboard -t image/png -o > $where.png && \
-	cjxl --lossless_jpeg=1 $where.png $where.jxl && rm $where.png || echo "error saving pic"
-}
-
-sa
+echo -n "$RANDOM$RANDOM" > /tmp/r && \
+where="xclip-$(cat /tmp/r)" && \
+xclip -selection clipboard -t image/png -o > $where.png && \
+cjxl --lossless_jpeg=1 $where.png $where.jxl && rm $where.png || echo "error saving pic"
