massive changes agian

diff --git a/sa b/sa
--- a/sa
+++ b/sa
@@ -2,5 +2,11 @@
 
 echo -n "$RANDOM$RANDOM" > /tmp/r && \
 where="xclip-$(cat /tmp/r)" && \
-xclip -selection clipboard -t image/png -o > $where.png && \
-cjxl --lossless_jpeg=1 $where.png $where.jxl && rm $where.png || echo "error saving pic"
+
+if [ "$(pwd)" != "$HOME" ]; then
+	xclip -selection clipboard -t image/png -o > $where.png && \
+	cjxl --lossless_jpeg=1 $where.png $where.jxl && rm $where.png || echo "error saving pic"
+else
+	xclip -selection clipboard -t image/png -o > ~/Desktop/$where.png && \
+	cjxl --lossless_jpeg=1 ~/Desktop/$where.png ~/Desktop/$where.jxl && rm ~/Desktop/$where.png || notify-send "error saving pic"
+fi
